---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: todos
spec:
  host: todos-app-istio-system.apps.ocp1-dev.pdc.thriveai.kp.org
  port:
    targetPort: http2
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: istio-ingressgateway
    weight: 100
  wildcardPolicy: None