apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todos.webui.name" . }}
  labels:
    {{- include "todos.webui.labels" . | nindent 4 }}
data:
  TODOS_WEBUI_PLACEHOLDER: {{ .Values.todos.webui.placeholder | quote }}
  SPRING_SECURITY_USER_NAME: {{ .Values.todos.webui.username | quote }}
