apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todos.mysql.name" . }}
  labels:
  {{- include "todos.mysql.labels" . | nindent 4 }}
data:
  MYSQL_USER: {{ .Values.todos.mysql.secrets.user }}
  MYSQL_PASSWORD: {{ .Values.todos.mysql.secrets.password }}