apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todos.mysql.name" . }}
  labels:
  {{- include "todos.mysql.labels" . | nindent 4 }}
data:
  MYSQL_USER: dXNlcjE=
  MYSQL_PASSWORD: bXlzcWwxMjM=