apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todos.db.name" . }}
  labels:
    {{- include "todos.db.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.todos.db.replicaCount }}
  selector:
    matchLabels:
      {{- include "todos.db.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.todos.db.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "todos.db.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.todos.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "todos.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.todos.db.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.todos.db.name }}
          securityContext:
            {{- toYaml .Values.todos.db.securityContext | nindent 12 }}
          image: {{ .Values.todos.db.image.repository }}:{{ .Values.todos.db.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.todos.db.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "todos.db.name" . }}
            - secretRef:
                name: {{ include "todos.db.name" . }}
          ports:
            - name: tcp
              containerPort: {{ .Values.todos.db.services.internal.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.todos.db.resources | nindent 12 }}