apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todos.db.name" . }}
  labels:
  {{- include "todos.db.labels" . | nindent 4 }}
data:
  MYSQL_USER: dXNlcjE=
  MYSQL_PASSWORD: bXlzcWwxMjM=
  MYSQL_ROOT_PASSWORD: bXlzcWwxMjM=