apiVersion: v1
kind: Pod
metadata:
  name: httpie
spec:
  containers:
    - name: httpie
      image: quay.io/corbsmartin/httpie:3.2.1
      command:
        - sleep
        - "3600"
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
