{{ if and .Values.istio.enabled .Values.istio.gateway.enabled  }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "todos.webui.name" . }}
  labels:
  {{- include "todos.webui.labels" . | nindent 4 }}
spec:
  hosts:
  {{ toYaml .Values.istio.gateway.hosts }}
  gateways:
    - {{ .Values.istio.gateway.name }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ include "todos.webui.name" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.todos.webui.services.internal.port }}
  {{ end }}