# ----------------------------------------------------------------------------------------------------------------------
# System level properties
# ----------------------------------------------------------------------------------------------------------------------
system:
  name: todos
  version: 1.0.0
# ----------------------------------------------------------------------------------------------------------------------
# OPC cluster properties
# ----------------------------------------------------------------------------------------------------------------------
cluster:
  name: crc.testing
  region: local
# ----------------------------------------------------------------------------------------------------------------------
# OpenShift service mesh (aka istio) properties
#   NOTE:
#   1) istio.gateway.hosts must match route.host
# ----------------------------------------------------------------------------------------------------------------------
istio:
  enabled: true
  gateway:
    name: todos-gateway
    selector: ingressgateway
    hosts:
      - "todos.apps-crc.testing"
    tls:
      enabled: false
      mode: SIMPLE
      credentialName: istio-certs
      httpsRedirect: true
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      caCertificates: /etc/istio/ingressgateway-ca-certs/ca-chain.cert.pem
  virtualservice:
    name: todos
# ----------------------------------------------------------------------------------------------------------------------
# OpenShift ingress route for the service mesh gateway
#   NOTE:
#   1) route.host must match istio.gateway.hosts
# ----------------------------------------------------------------------------------------------------------------------
route:
  enabled: false
  name: todos
  namespace: istio-system
  host: todos.apps-crc.testing
  targetPort: http
  wildcard:
    policy: None
  tls:
    termination: edge
    insecurePolicy: Redirect
# ----------------------------------------------------------------------------------------------------------------------
# Todos application properties
# ----------------------------------------------------------------------------------------------------------------------
todos:
  imagePullSecrets: []
  serviceAccount:
    annotations: { }
    name: todos-sa
  webui:
    name: todos-webui
    replicaCount: 1
    podAnnotations:
      sidecar.istio.io/inject: "true"
    podSecurityContext: {}
    securityContext: {}
    resources: {}
    services:
      internal:
        enabled: true
        name: http
        protocol: TCP
        type: ClusterIP
        port: 8080
        targetPort: 8080
      external:
        enabled: false
        name: http-lb
        protocol: TCP
        type: LoadBalancer
        port: 8080
        targetPort: 8080
    image:
      repository: quay.io/corbsmartin/todos-webui
      tag: 1.0.2
      pullPolicy: Always
    envs:
      username: "User1"
      placeholder: "What shall you do today?"
    livenessPath: "/actuator/health/liveness"
    readinessPath: "/actuator/health/readiness"
  mysql:
    name: todos-mysql
    replicaCount: 1
    podAnnotations:
      sidecar.istio.io/inject: "true"
    podSecurityContext: {}
    securityContext: {}
    resources: {}
    services:
      internal:
        enabled: true
        name: http
        protocol: TCP
        type: ClusterIP
        port: 8080
        targetPort: 8080
      external:
        enabled: false
        name: http-lb
        protocol: TCP
        type: LoadBalancer
        port: 8080
        targetPort: 8080
    image:
      repository: quay.io/corbsmartin/todos-mysql
      tag: 1.0.0
      pullPolicy: Always
    envs:
      database: todos
    secrets:
      user: dXNlcjE=
      password: bXlzcWwxMjM=
    livenessPath: "/actuator/health/liveness"
    readinessPath: "/actuator/health/readiness"
  db:
    name: todos-db
    replicaCount: 1
    podAnnotations:
      sidecar.istio.io/inject: "true"
    podSecurityContext: {}
    securityContext: {}
    resources: {}
    services:
      internal:
        enabled: true
        name: http
        protocol: TCP
        type: ClusterIP
        port: 3306
        targetPort: 3306
      external:
        enabled: false
        name: http-lb
        protocol: TCP
        type: LoadBalancer
        port: 3306
        targetPort: 3306
    image:
      repository: registry.redhat.io/rhel8/mysql-80
      tag: latest
      pullPolicy: Always