---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "todos.serviceAccountName" . }}
  labels:
    {{- include "todos.labels" . | nindent 4 }}
  {{- with .Values.todos.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
